In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Sentiment Analysis on Student Feedback.csv')
df

,Timestamp,Course Code,Faculty,Feedback,Previous Experience,Gender,Attendance,Course Difficulty,Study Hours (per week),Overall Satisfaction,Department,Unnamed: 11
0,2023/05/21 3:29:49 AM MDT,CPE 321,3,"The man is too fast in his teaching,he clearly...",No,Male,Regular,Challenging,21 hours,5,Yes,20/30GR072
1,2023/05/21 3:39:59 AM MDT,CPE 331,2,The class is dry but he really puts in efforts,Yes,Male,Regular,Moderate,7,8,Yes,19/30GR010
2,2023/05/21 3:57:54 AM MDT,CPE 321,4,The course is shit and it's a threat to my bra...,No,Male,Regular,Challenging,7hrs,4,Yes,20/30GR073
3,2023/05/21 4:52:08 AM MDT,CPE 321,3,"He no try at all, didn’t teach well.",No,Male,Regular,Challenging,12,1,Yes,NaN
4,2023/05/21 5:24:33 AM MDT,CPE 321,3,Ogbeni you sef know as e dae go,Yes,Male,Occasional,Difficult,How you want take study something wey you head...,0,Yes,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023/05/30 2:56:07 PM MDT,GSE 301,2,easy and no wahala,Yes,Female,Regular,Easy,9,8,Yes,NaN
96,2023/05/30 2:57:17 PM MDT,CPE 321,2,terrible way of teaching with the I-dont-care ...,No,Female,Irregular,Difficult,4,0,Yes,NaN
97,2023/05/30 3:02:16 PM MDT,CPE 341,1,do not like coding,No,Male,Irregular,Difficult,0,0,Yes,NaN
98,2023/05/30 3:03:39 PM MDT,CPE 381,3,this practical is hard on top 1 unit course haba,No,Female,Regular,Difficult,5,0,Yes,NaN
99,2023/05/30 3:05:02 PM MDT,CPE 321,3,"not the right way to teach, Mr Akanni",No,Male,Occasional,Difficult,3,0,Yes,NaN

In [6]:
df['Faculty '].unique()

array([3, 2, 4, 1], dtype=int64)

In [7]:
def FacultyintToName(n):
    if n == 1:
        return "Prof. Sunil"
    elif n == 2:
        return "Prof. Reha"
    elif n == 3:
        return "Prof. Ujwal"
    else:
        return "Prof. Kanishik"

In [10]:
df['Faculty '] = df['Faculty '].map(FacultyintToName)

In [17]:
df = df.drop('Timestamp', axis=1)

In [18]:
df

,Course Code,Faculty,Feedback,Previous Experience,Gender,Attendance,Course Difficulty,Study Hours (per week),Overall Satisfaction,Department,Unnamed: 11
0,CPE 321,Prof. Ujwal,"The man is too fast in his teaching,he clearly...",No,Male,Regular,Challenging,21 hours,5,Yes,20/30GR072
1,CPE 331,Prof. Reha,The class is dry but he really puts in efforts,Yes,Male,Regular,Moderate,7,8,Yes,19/30GR010
2,CPE 321,Prof. Kanishik,The course is shit and it's a threat to my bra...,No,Male,Regular,Challenging,7hrs,4,Yes,20/30GR073
3,CPE 321,Prof. Ujwal,"He no try at all, didn’t teach well.",No,Male,Regular,Challenging,12,1,Yes,NaN
4,CPE 321,Prof. Ujwal,Ogbeni you sef know as e dae go,Yes,Male,Occasional,Difficult,How you want take study something wey you head...,0,Yes,NaN
...,...,...,...,...,...,...,...,...,...,...,...
95,GSE 301,Prof. Reha,easy and no wahala,Yes,Female,Regular,Easy,9,8,Yes,NaN
96,CPE 321,Prof. Reha,terrible way of teaching with the I-dont-care ...,No,Female,Irregular,Difficult,4,0,Yes,NaN
97,CPE 341,Prof. Sunil,do not like coding,No,Male,Irregular,Difficult,0,0,Yes,NaN
98,CPE 381,Prof. Ujwal,this practical is hard on top 1 unit course haba,No,Female,Regular,Difficult,5,0,Yes,NaN
99,CPE 321,Prof. Ujwal,"not the right way to teach, Mr Akanni",No,Male,Occasional,Difficult,3,0,Yes,NaN

In [14]:
df['Course Code'].unique()

array(['CPE 321', 'CPE 331', 'MEE 361', 'CPE 311', 'CPE 341', 'CPE 381',
       'GSE 301'], dtype=object)

In [28]:
def Gender(st:str):
    if st == "Prof. Reha":
        return "Female"
    else:
        return "Male"

In [30]:
df['Gender'] = df["Faculty "].apply(Gender)
df

,Course Code,Faculty,Feedback,Previous Experience,Gender,Attendance,Course Difficulty,Study Hours (per week),Overall Satisfaction,Department,Unnamed: 11
0,CPE 321,Prof. Ujwal,"The man is too fast in his teaching,he clearly...",No,Male,Regular,Challenging,21 hours,5,Yes,20/30GR072
1,CPE 331,Prof. Reha,The class is dry but he really puts in efforts,Yes,Female,Regular,Moderate,7,8,Yes,19/30GR010
2,CPE 321,Prof. Kanishik,The course is shit and it's a threat to my bra...,No,Male,Regular,Challenging,7hrs,4,Yes,20/30GR073
3,CPE 321,Prof. Ujwal,"He no try at all, didn’t teach well.",No,Male,Regular,Challenging,12,1,Yes,NaN
4,CPE 321,Prof. Ujwal,Ogbeni you sef know as e dae go,Yes,Male,Occasional,Difficult,How you want take study something wey you head...,0,Yes,NaN
...,...,...,...,...,...,...,...,...,...,...,...
95,GSE 301,Prof. Reha,easy and no wahala,Yes,Female,Regular,Easy,9,8,Yes,NaN
96,CPE 321,Prof. Reha,terrible way of teaching with the I-dont-care ...,No,Female,Irregular,Difficult,4,0,Yes,NaN
97,CPE 341,Prof. Sunil,do not like coding,No,Male,Irregular,Difficult,0,0,Yes,NaN
98,CPE 381,Prof. Ujwal,this practical is hard on top 1 unit course haba,No,Male,Regular,Difficult,5,0,Yes,NaN
99,CPE 321,Prof. Ujwal,"not the right way to teach, Mr Akanni",No,Male,Occasional,Difficult,3,0,Yes,NaN

In [31]:
df['Study Hours (per week)'].unique()

array(['21 hours', '7', '7hrs', '12',
       'How you want take study something wey you head no carry ', '9',
       '3', '0', '4', '5', '6', '0.5', 'I don’t know', '2', '10', '1',
       '4 hours ', '8', '11', '15', '14', '18', '19', '16', '17', '13'],
      dtype=object)

In [41]:
import re

def extract_numbers(text: str):
    # Find all sequences of digits in the string
    numbers = re.findall(r'\d+', text)
    # Return the first number found, or 0 if no numbers are found
    return int(numbers[0]) if numbers else 0

In [42]:
df["Study Hours (per week)"] = df['Study Hours (per week)'].apply(extract_numbers)
df

,Course Code,Faculty,Feedback,Previous Experience,Gender,Attendance,Course Difficulty,Study Hours (per week),Overall Satisfaction,Department,Unnamed: 11
0,CPE 321,Prof. Ujwal,"The man is too fast in his teaching,he clearly...",No,Male,Regular,Challenging,21,5,Yes,20/30GR072
1,CPE 331,Prof. Reha,The class is dry but he really puts in efforts,Yes,Female,Regular,Moderate,7,8,Yes,19/30GR010
2,CPE 321,Prof. Kanishik,The course is shit and it's a threat to my bra...,No,Male,Regular,Challenging,7,4,Yes,20/30GR073
3,CPE 321,Prof. Ujwal,"He no try at all, didn’t teach well.",No,Male,Regular,Challenging,12,1,Yes,NaN
4,CPE 321,Prof. Ujwal,Ogbeni you sef know as e dae go,Yes,Male,Occasional,Difficult,0,0,Yes,NaN
...,...,...,...,...,...,...,...,...,...,...,...
95,GSE 301,Prof. Reha,easy and no wahala,Yes,Female,Regular,Easy,9,8,Yes,NaN
96,CPE 321,Prof. Reha,terrible way of teaching with the I-dont-care ...,No,Female,Irregular,Difficult,4,0,Yes,NaN
97,CPE 341,Prof. Sunil,do not like coding,No,Male,Irregular,Difficult,0,0,Yes,NaN
98,CPE 381,Prof. Ujwal,this practical is hard on top 1 unit course haba,No,Male,Regular,Difficult,5,0,Yes,NaN
99,CPE 321,Prof. Ujwal,"not the right way to teach, Mr Akanni",No,Male,Occasional,Difficult,3,0,Yes,NaN

In [44]:
df = df.drop('Unnamed: 11', axis=1)

In [45]:
df

,Course Code,Faculty,Feedback,Previous Experience,Gender,Attendance,Course Difficulty,Study Hours (per week),Overall Satisfaction,Department
0,CPE 321,Prof. Ujwal,"The man is too fast in his teaching,he clearly...",No,Male,Regular,Challenging,21,5,Yes
1,CPE 331,Prof. Reha,The class is dry but he really puts in efforts,Yes,Female,Regular,Moderate,7,8,Yes
2,CPE 321,Prof. Kanishik,The course is shit and it's a threat to my bra...,No,Male,Regular,Challenging,7,4,Yes
3,CPE 321,Prof. Ujwal,"He no try at all, didn’t teach well.",No,Male,Regular,Challenging,12,1,Yes
4,CPE 321,Prof. Ujwal,Ogbeni you sef know as e dae go,Yes,Male,Occasional,Difficult,0,0,Yes
...,...,...,...,...,...,...,...,...,...,...
95,GSE 301,Prof. Reha,easy and no wahala,Yes,Female,Regular,Easy,9,8,Yes
96,CPE 321,Prof. Reha,terrible way of teaching with the I-dont-care ...,No,Female,Irregular,Difficult,4,0,Yes
97,CPE 341,Prof. Sunil,do not like coding,No,Male,Irregular,Difficult,0,0,Yes
98,CPE 381,Prof. Ujwal,this practical is hard on top 1 unit course haba,No,Male,Regular,Difficult,5,0,Yes
99,CPE 321,Prof. Ujwal,"not the right way to teach, Mr Akanni",No,Male,Occasional,Difficult,3,0,Yes

In [46]:
df.to_csv("DAAEHDataset.csv")